### ISSUE TITLE
Com评论组件报错及解决办法

### ISSUE THREAD

**Issue by hujesse83** [andochiwa/Online-Education-Frontend-web#1]
参考了你的评论组件, 发现我怎样都不能启动, 还一直报错->ReferenceError: document is not defined.
后来在这篇博客找到了解决方案
https://www.jianshu.com/p/bc2f62f2f078.

**Comment by hujesse83** [comment]
在<comment>标签加<no-ssr></no-ssr>成功解决.

**Comment by andochiwa** [comment]
我这边没有使用 mavon-editor 这个组件，评论组件指的是 hbl-comment 这个组件吗？因为我测试过几遍也没有发现有报这个错误

**Comment by hujesse83** [comment]
对的我是使用hbl-comment 组件的时候报的错, 我提这个issue顺便给可以给报错的同学提供一个解决方案.
